[package]
name = "dijkstra-map-gd"
version = "0.1.0"
authors = ["Astrale", "Matej Sloboda"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9"

[build-dependencies]
gdnative-doc = { path = "../.." }
